# Запуск контейнеров:
# docker compose --profile --pull always pi up -d

version: '3.8'
name: smarthome
services:

  # system ---------------------------------------------------------------------

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    hostname: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${pgadmin_email}
      - PGADMIN_DEFAULT_PASSWORD=${pgadmin_password}
    ports:
      - "${pgadmin_port}:80"
    profiles:
      - pi
    restart: always
    volumes:
      - sh_pgadmin_volume:/var/lib/pgadmin

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "8001:9000"
    restart: always
    profiles:
      - system
    volumes:
      - portainer_data_volume:/data
      - /var/run/docker.sock:/var/run/docker.sock

  # pi -------------------------------------------------------------------------

  sh_deconz_hub:
    image: docker-registry:5000/smarthome/sh_deconz_hub
    container_name: sh_deconz_hub
    hostname: sh_deconz_hub
    devices:
      - /dev/ttyACM0
    environment:
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PASSWORD=${deconz_hub_vnc_password}
    ports:
      - "${deconz_hub_port_api}:80"
      - "${deconz_hub_port_ws}:443"
      - "${deconz_hub_port_vnc}:5900"
    privileged: true
    profiles:
      - pi
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - sh_deconz_hub_volume:/opt/deCONZ

  sh_db:
    image: docker-registry:5000/smarthome/sh_db
    container_name: sh_db
    hostname: sh_db
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_USER=${db_user}
      - POSTGRES_PASSWORD=${db_password}
    ports:
      - "${db_port}:5432"
    profiles:
      - pi
    volumes:
      - sh_db_volume:/home/postgres/pgdata/data
      - ./db/postgresql.conf:/etc/postgresql/postgresql.conf

  sh_driver_deconz:
    image: docker-registry:5000/smarthome/sh_driver_deconz
    container_name: sh_driver_deconz
    hostname: sh_driver_deconz
    ports:
      - "${driver_deconz_port}:${driver_deconz_port}"
    profiles:
      - pi
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .:/root/code

  sh_redis:
    image: docker-registry:5000/smarthome/sh_redis
    container_name: sh_redis
    hostname: sh_redis
    ports:
      - "${redis_port}:6379"
    profiles:
      - pi

  sh_setup:
    image: docker-registry:5000/smarthome/sh_setup
    container_name: sh_setup
    hostname: sh_setup
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .:/root/code

volumes:
  sh_db_volume:
    name: sh_db_volume
  sh_pgadmin_volume:
    name: sh_pgadmin_volume
  sh_deconz_hub_volume:
    name: sh_deconz_hub_volume
  portainer_data_volume:
    name: portainer_data_volume
  docker_registry_volume:
    name: docker_registry_volume
