# Запуск контейнеров:
# docker compose --profile --pull always pi up -d

version: '3.8'
name: smarthome
services:
  sh_deconz_hub:
    image: konstantindudersky/sh_deconz_hub
    container_name: sh_deconz_hub
    hostname: sh_deconz_hub
    devices:
      - /dev/ttyACM0
    environment:
      - DECONZ_VNC_MODE=1
    ports:
      - "${deconz_hub_port_api}:80"
      - "${deconz_hub_port_ws}:443"
      - "${deconz_hub_port_vnc}:5900"
    privileged: true
    profiles:
      - pi
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - sh_deconz_hub_volume:/opt/deCONZ
  sh_db:
    image: konstantindudersky/sh_db
    container_name: sh_db
    hostname: sh_db
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_USER=${db_user}
      - POSTGRES_PASSWORD=${db_password}
    ports:
      - "${db_port}:5432"
    profiles:
      - pi
    volumes:
      - sh_db_volume:/home/postgres/pgdata/data
      - ./db/postgresql.conf:/etc/postgresql/postgresql.conf
  sh_driver_deconz:
    image: konstantindudersky/sh_driver_deconz
    container_name: sh_driver_deconz
    hostname: sh_driver_deconz
    ports:
      - "${driver_deconz_port}:8000"
    profiles:
      - pi
        # coca_webapp:
        #   image: inosat/coca_webapp
        #   container_name: coca_webapp
        #   build:
        #     context: .
        #     dockerfile: webapp/Dockerfile
        #     network: 'host'
        #     target: webapp
        #   env_file: .env
        #   ports:
        #     - "${service_webapp_port}:443"
        #   profiles:
        #     - server
        #   volumes:
        #     - ${ssl_certfile}:/root/certs/server.crt
        #     - ${ssl_keyfile}:/root/certs/server.key
        #     - ./webapp/dist/webapp:/usr/share/nginx/html
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    hostname: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${pgadmin_email}
      - PGADMIN_DEFAULT_PASSWORD=${pgadmin_password}
    ports:
      - "${pgadmin_port}:80"
    profiles:
      - pi
    volumes:
      - sh_pgadmin_volume:/var/lib/pgadmin
volumes:
  sh_db_volume:
    name: sh_db_volume
  sh_pgadmin_volume:
    name: sh_pgadmin_volume
  sh_deconz_hub_volume:
    name: sh_deconz_hub_volume
