# Запуск контейнеров:
# docker compose --profile pi --pull always up -d

version: '3.8'
name: smarthome

services:

  db:
    container_name: db
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_USER=${db_user}
      - POSTGRES_PASSWORD=${db_password}
    hostname: db
    image: docker-registry:5000/smarthome/db
    ports:
      - "${db_port}:5432"
    profiles:
      - pi
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./db/postgresql.conf:/etc/postgresql/postgresql.conf

  deconz_hub:
    container_name: deconz_hub
    devices:
      - /dev/ttyACM0
    environment:
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PASSWORD=${deconz_hub_vnc_password}
    hostname: deconz_hub
    image: docker-registry:5000/smarthome/deconz_hub
    ports:
      - "${deconz_hub_port_api}:80"
      - "${deconz_hub_port_ws}:443"
      - "${deconz_hub_port_vnc}:5900"
    privileged: true
    profiles:
      - pi
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - deconz_hub_volume:/opt/deCONZ

  driver_deconz:
    container_name: driver_deconz
    depends_on:
      - deconz_hub
      - redis
    hostname: driver_deconz
    image: docker-registry:5000/smarthome/driver_deconz
    ports:
      - "${driver_deconz_port}:${driver_deconz_port}"
    profiles:
      - pi
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .:/root/code

  grafana:
    container_name: grafana
    depends_on:
      - redis
      - db
    hostname: grafana
    image: docker-registry:5000/smarthome/grafana
    ports:
      - "${grafana_port}:3000"
    profiles:
      - pi
    volumes:
      - grafana_volume:/var/lib/grafana

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${pgadmin_email}
      - PGADMIN_DEFAULT_PASSWORD=${pgadmin_password}
    hostname: pgadmin
    image: docker-registry:5000/smarthome/pgadmin
    ports:
      - "${pgadmin_port}:80"
    restart: always
    volumes:
      - pgadmin_volume:/var/lib/pgadmin

  portainer:
    container_name: portainer
    hostname: portainer
    image: docker-registry:5000/smarthome/portainer
    ports:
      - "8001:9000"
    profiles:
      - system
    restart: always
    volumes:
      - portainer_data_volume:/data
      - /var/run/docker.sock:/var/run/docker.sock

  redis:
    container_name: redis
    hostname: redis
    image: docker-registry:5000/smarthome/redis
    ports:
      - "${redis_port}:6379"
      - "${redis_ui_port}:8001"
    profiles:
      - pi

  redis_to_db:
    container_name: redis_to_db
    depends_on:
      - redis
      - db
    hostname: redis_to_db
    image: docker-registry:5000/smarthome/redis_to_db
    profiles:
      - pi
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .:/root/code

  setup:
    container_name: setup
    hostname: setup
    image: docker-registry:5000/smarthome/setup
    profiles:
      - nostart
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .:/root/code

volumes:
  db_volume:
    name: db_volume
  pgadmin_volume:
    name: pgadmin_volume
  deconz_hub_volume:
    name: deconz_hub_volume
  portainer_data_volume:
    name: portainer_data_volume
  grafana_volume:
    name: grafana_volume
