@startuml

!include C4_Dynamic.puml
!include <tupadr3/common>
!include <tupadr3/font-awesome-5/sun>
!include <tupadr3/font-awesome-5/lightbulb>
!include <tupadr3/font-awesome-5/thermometer>
!include <tupadr3/devicons/postgresql>
!include <tupadr3/font-awesome-5/telegram>
!include <tupadr3/devicons/angular>
!include <tupadr3/devicons/python>
!include <tupadr3/font-awesome-5/server>
title C4

System_Boundary(140021643460080, $label="smarthome"){
	Container(140021643455136, $label="web app", $techn="angular", $descr="", $sprite="angular")
Container(140021643455664, $label="desktop app", $techn="angular, tauri", $descr="", $sprite="angular")
Container_Ext(140021643460560, $label="deconz_hub", $techn="REST API, websockets", $descr="", $sprite="server")
Container_Boundary(140021643460176, $label="raspberry"){
	Component(140021643457248, $label="API", $techn="FastAPI", $descr="", $sprite="python")
Component(140021643458928, $label="weather-service", $techn="Python", $descr="", $sprite="python")
Component(140021643460416, $label="driver_deconz", $techn="httpx, websockets", $descr="", $sprite="python")
ComponentDb(140021643460272, $label="db", $techn="PostgreSQL+TimescaleDB", $descr="Настройки, архивы", $sprite="postgresql")
Component(140021643459072, $label="yeelight-service", $techn="asyncio stream", $descr="", $sprite="python")
Component(140021643459216, $label="telegram-service", $techn="telegram", $descr="", $sprite="python")

}
Container_Ext(140021643456192, $label="Zigbee sensors", $techn="T, P, ...", $descr="", $sprite="thermometer")
Container_Ext(140021643457104, $label="Yeelight bulbs", $techn="Yeelight", $descr="", $sprite="lightbulb")

}
System_Ext(140021643459360, $label="Weather", $descr="", $sprite="sun")
System_Ext(140021643459504, $label="Telegram", $descr="", $sprite="telegram")



Rel(140021643455136, 140021643457248, "Uses", "http", "")
Rel(140021643455664, 140021643457248, "Uses", "http", "")
Rel_Back(140021643459360, 140021643458928, "Uses", "http", "")
BiRel(140021643460416, 140021643460560, "Uses", "http", "")
Rel(140021643460560, 140021643456192, "Uses", "zigbee", "")
Rel(140021643459072, 140021643457104, "R/W", "http,Wi-Fi", "")
Rel_Back(140021643459504, 140021643459216, "send", "http", "")
SHOW_LEGEND()
@enduml
