"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING, Type
from uvicorn.supervisors.basereload import BaseReload
from uvicorn.supervisors.multiprocess import Multiprocess

if TYPE_CHECKING:
    ChangeReload: Type[BaseReload]
    ...
else:
    ...
__all__ = ["Multiprocess", "ChangeReload"]
