"""
This type stub file was generated by pyright.
"""

from socket import socket
from types import FrameType
from typing import Callable, List, Optional
from uvicorn.config import Config

HANDLED_SIGNALS = ...
logger = ...
class Multiprocess:
    def __init__(self, config: Config, target: Callable[[Optional[List[socket]]], None], sockets: List[socket]) -> None:
        ...
    
    def signal_handler(self, sig: int, frame: Optional[FrameType]) -> None:
        """
        A signal handler that is registered with the parent process.
        """
        ...
    
    def run(self) -> None:
        ...
    
    def startup(self) -> None:
        ...
    
    def shutdown(self) -> None:
        ...
    


