@startuml

!include C4_Dynamic.puml
!include <tupadr3/common>
!include <tupadr3/devicons/sqllite>
!include <tupadr3/font-awesome-5/thermometer>
!include <tupadr3/devicons/angular>
!include <tupadr3/devicons/python>
!include <tupadr3/devicons/postgresql>
!include <tupadr3/font-awesome-5/sun>
!include <tupadr3/font-awesome-5/server>
title C4

System_Boundary(139798168931632, $label="smarthome"){
	Container(139798170039008, $label="web app", $techn="angular", $descr="", $sprite="angular")
Container(139798168930432, $label="desktop app", $techn="angular, tauri", $descr="", $sprite="angular")
Container_Ext(139798168930624, $label="Deconz", $techn="REST API, websockets", $descr="", $sprite="server")
Container_Boundary(139798168931392, $label="Server"){
	Component(139798168930912, $label="API", $techn="FastAPI", $descr="", $sprite="python")
Component(139798168931056, $label="weather-service", $techn="Python", $descr="", $sprite="python")
Component(139798168931200, $label="deconz-service", $techn="aiohttp", $descr="", $sprite="python")
ComponentDb(139798168931344, $label="DB", $techn="SQLite", $descr="Для сохранения состояния и настроек", $sprite="sqllite")

}
ContainerDb(139798168931536, $label="DB", $techn="PostgreSQL+TimescaleDB", $descr="Для архивов", $sprite="postgresql")
Container_Ext(139798168930768, $label="Zigbee sensors", $techn="T, P, ...", $descr="", $sprite="thermometer")

}
System_Ext(139798168931776, $label="Weather", $descr="", $sprite="sun")



Rel(139798170039008, 139798168930912, "Uses", "http", "")
Rel(139798168930432, 139798168930912, "Uses", "http", "")
Rel(139798168931056, 139798168931776, "Uses", "http", "")
Rel(139798168931200, 139798168930624, "Uses", "http", "")
Rel(139798168930624, 139798168930768, "Uses", "zigbee", "")
Rel(139798168931392, 139798168931536, "R/W", "sqlalchemy+psycopg", "")
SHOW_LEGEND()
@enduml
