@startuml

!include C4_Dynamic.puml
!include <tupadr3/common>
!include <tupadr3/devicons/sqllite>
!include <tupadr3/font-awesome-5/sun>
!include <tupadr3/devicons/angular>
!include <tupadr3/font-awesome-5/thermometer>
!include <tupadr3/font-awesome-5/server>
!include <tupadr3/devicons/postgresql>
!include <tupadr3/devicons/python>
title C4

System_Boundary(140424949845728, $label="smarthome"){
	Container(140424950952912, $label="web app", $techn="angular", $descr="", $sprite="angular")
Container(140424949844528, $label="desktop app", $techn="angular, tauri", $descr="", $sprite="angular")
Container_Ext(140424949844720, $label="Deconz", $techn="REST API, websockets", $descr="", $sprite="server")
Container_Boundary(140424949845488, $label="Server"){
	Component(140424949845008, $label="API", $techn="FastAPI", $descr="", $sprite="python")
Component(140424949845152, $label="weather-service", $techn="Python", $descr="", $sprite="python")
Component(140424949845296, $label="deconz-service", $techn="aiohttp", $descr="", $sprite="python")
ComponentDb(140424949845440, $label="DB", $techn="SQLite", $descr="Для сохранения состояния и настроек", $sprite="sqllite")

}
ContainerDb(140424949845632, $label="DB", $techn="PostgreSQL+TimescaleDB", $descr="Для архивов", $sprite="postgresql")
Container_Ext(140424949844864, $label="Zigbee sensors", $techn="T, P, ...", $descr="", $sprite="thermometer")

}
System_Ext(140424949845872, $label="Weather", $descr="", $sprite="sun")



Rel(140424950952912, 140424949845008, "Uses", "http", "")
Rel(140424949844528, 140424949845008, "Uses", "http", "")
Rel(140424949845152, 140424949845872, "Uses", "http", "")
Rel(140424949845296, 140424949844720, "Uses", "http", "")
Rel(140424949844720, 140424949844864, "Uses", "zigbee", "")
Rel(140424949845488, 140424949845632, "R/W", "sqlalchemy+psycopg", "")
SHOW_LEGEND()
@enduml
