keepEmptyPriority: false
code:
  include_lists:
    - TODO
    - DOING
    - DONE
    - PLANNING
    - FIXME
    - ARCHIVE
    - HACK
    - CHANGED
    - XXX
    - IDEA
    - NOTE
    - REVIEW
    - TEST
lists:
  - name: What's Due?
    hidden: true
    ignore: false
    filter: 'dueDate < "${tomorrow at 6AM}" AND list != DONE +dueDate +order'
    id: 0
  - name: TODO
    hidden: false
    ignore: false
  - name: DOING
    hidden: false
    ignore: false
  - name: TEST
    hidden: false
    ignore: false
  - name: DONE
    hidden: false
    ignore: true
  - name: Recently Completed
    hidden: false
    ignore: false
    filter: 'completedDate > "${14 days ago}" -completed'
    id: 1
  - name: HACK
    hidden: false
    ignore: false
  - name: XXX
    hidden: false
    ignore: false
  - name: FIXME
    hidden: false
    ignore: false
settings:
  openIn: default
  customOpenIn: ''
  editorTheme: blackboard
  journalType: Single File
  journalPath: null
  appendNewCardsTo: imdone-tasks.md
  newCardSyntax: MARKDOWN
  replaceSpacesWith: '-'
  plugins:
    devMode: false
  filteredLists:
    - filter: 'dueDate < "${tomorrow at 6AM}" AND list != DONE +dueDate +order'
      name: What's Due?
    - filter: 'completedDate > "${7 days ago}" -completed'
      name: Recently Completed
  journalTemplate: null
  theme: dark
  addCheckBoxTasks: false
  name: smarthome
  views:
    - id: default
      filter: ''
  cards:
    colors: []
    template: |

      <!--
      created:${timestamp}
      -->
    trackChanges: false
    metaNewLine: false
    addCompletedMeta: true
    addCheckBoxTasks: false
    doneList: DONE
    taskPrefix: '#'
    tagPrefix: '#'
    metaSep: ':'
    maxLines: 6
    addNewCardsToTop: true
    defaultList: TODO
    computed: !<tag:yaml.org,2002:js/undefined> ''
